version: '3.1'
services:
  postgres:
    #image: gammatech/pg_mongo
    image: postgres
    #image: msshahanshah/postgres_fdw:4
    container_name: postgres
    environment:
      - POSTGRES_USER=pgsql
      - POSTGRES_PASSWORD=12345678
    volumes:
      - './data:/var/lib/postgresql/data'
      - './dumps:/dumps'
    ports:
      - "5432:5432"
    # networks:
    #   - bridgec
