version: '3.1'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=Abcd_1234
    ports:
      - "27017:27017"
    volumes:
      - ./db_mongo_new:/data/db